USE givas;
CREATE TABLE CUSTOMER(
CUST_ID INT IDENTITY(101,1) NOT NULL PRIMARY KEY,
LAST_NAME VARCHAR(20),
FIRST_NAME VARCHAR(20),
ADDRSS VARCHAR(255),
PHONE VARCHAR(15),
AGE INT)


CREATE TABLE ACCOUNT(
ACC_NO  INT IDENTITY(001,1) NOT NULL PRIMARY KEY,
ACC_TYPE VARCHAR(20),
BALANCE  FLOAT CHECK(BALANCE>=100),
CUST_ID INT, FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(CUST_ID),
);

SELECT * FROM ACCOUNT;
SELECT * FROM CUSTOMER;
INSERT INTO CUSTOMER (LAST_NAME,FIRST_NAME,ADDRSS,PHONE,AGE) VALUES ('SHENOY','SUPPI','KARNATAKA,UDUPI',7895592657,20);
INSERT INTO CUSTOMER (LAST_NAME,FIRST_NAME,ADDRSS,PHONE,AGE) VALUES ('RAI','SHAM','KARNATAKA,MANGLORE',9789052657,25);
INSERT INTO CUSTOMER (LAST_NAME,FIRST_NAME,ADDRSS,PHONE,AGE) VALUES ('BHAGATH','SHARMA','MUMBAI,THANE',8789092657,40);
INSERT INTO CUSTOMER (LAST_NAME,FIRST_NAME,ADDRSS,PHONE,AGE) VALUES ('SHETTY','BHARAT','TAMILNADU,TELANGANA',6789032657,60);

INSERT INTO ACCOUNT (ACC_TYPE, BALANCE, CUST_ID) VALUES ('SAVINGS',2000,101)
INSERT INTO ACCOUNT (ACC_TYPE,BALANCE,CUST_ID) VALUES ('FIXED',3020,102)
INSERT INTO ACCOUNT (ACC_TYPE,BALANCE,CUST_ID) VALUES ('SAVINGS',3440,103)
INSERT INTO ACCOUNT (ACC_TYPE,BALANCE,CUST_ID) VALUES ('SAVINGS',9000,104)

INSERT INTO ACCOUNT (ACC_TYPE,BALANCE,CUST_ID) VALUES ('SAVINGS',50,104)

ALTER TABLE CUSTOMER ADD PRIMARY KEY(CUST_ID)
ALTER TABLE ACCOUNT ADD FOREIGN KEY(CUST_ID) REFERENCES CUSTOMER(CUST_ID);
INSERT INTO ACCOUNT (ACC_NO,ACC_TYPE,BALANCE,CUST_ID) VALUES (14,'SAVINGS',9000,110)

SELECT ACC_TYPE,BALANCE INTO MODAC FROM ACCOUNT WHERE BALANCE>5000
SELECT*FROM MODACC
 DROP TABLE MODAC
 DROP TABLE CUSTOMER
DROP TABLE ACCOUNT;

ALTER TABLE CUSTOMER
ADD
	SSN VARCHAR(15);                                        
ALTER TABLE CUSTOMER DROP COLUMN SSN
ALTER TABLE CUSTOMER ALTER COLUMN PHONE VARCHAR(20)
INSERT INTO CUSTOMER (AGE) VALUES (20);
INSERT INTO CUSTOMER (AGE) VALUES (21);
INSERT INTO CUSTOMER (AGE) VALUES (60);
INSERT INTO CUSTOMER (AGE) VALUES (40);

ALTER TABLE CUSTOMER ADD CONSTRAINT AGE_LIMIT CHECK(AGE>1)
ALTER TABLE CUSTOMER ADD EMAIL VARCHAR(255); 
ALTER TABLE CUSTOMER ALTER COLUMN EMAIL VARCHAR(355)
UPDATE CUSTOMER SET EMAIL='hxhwwhx@gmail.com' where CUST_ID=118
ALTER TABLE CUSTOMER ADD CONSTRAINT valis_mail CHECK(EMAIL LIKE '%@gmail.com')
ALTER TABLE CUSTOMER ADD CONSTRAINT unique_mail UNIQUE(EMAIL)


UPDATE ACCOUNT SET BALANCE+=10000;

UPDATE CUSTOMER SET CUST_ID=108 WHERE CUST_ID=101

