SELECT * FROM ACCOUNT,CUSTOMER WHERE CUSTOMER.CUST_ID=ACCOUNT.CUST_ID

SELECT * FROM CUSTOMER C INNER JOIN ACCOUNT A ON A.CUST_ID=C.CUST_ID

SELECT * FROM CUSTOMER C,ACCOUNT A WHERE C.CUST_ID=A.CUST_ID

SELECT C.FIRST_NAME,C.AGE,A.ACC_NO,A.BALANCE FROM CUSTOMER C,ACCOUNT A WHERE C.CUST_ID=A.CUST_ID

SELECT * FROM CUSTOMER C LEFT JOIN ACCOUNT A ON A.CUST_ID=C.CUST_ID

SELECT * FROM CUSTOMER C RIGHT JOIN ACCOUNT A ON A.CUST_ID=C.CUST_ID

SELECT * FROM CUSTOMER C FULL OUTER JOIN ACCOUNT A ON A.CUST_ID=C.CUST_ID

CREATE TABLE CUSTOMER(
CUST_ID INT IDENTITY(101,1) NOT NULL,
LAST_NAME VARCHAR(20),
FIRST_NAME VARCHAR(20),
ADDRSS VARCHAR(255),
PHONE VARCHAR(15),
AGE INT)

CREATE TABLE AccountDeatails(
ACC_ID INT IDENTITY(101,1) NOT NULL PRIMARY KEY,
ACC_NO INT FOREIGN KEY(ACC_NO) REFERENCES ACCOUNT(ACC_NO),
AMOUNT INT,
TRANSACTION_REF BIGINT UNIQUE,
TRASACTION_TYPE  VARCHAR(15) CHECK(TRASACTION_TYPE IN ('CR','DB')))

DROP TABLE AccountDeatails

SELECT * FROM AccountDeatails

INSERT INTO AccountDeatails (ACC_NO,AMOUNT,TRANSACTION_REF,TRASACTION_TYPE) VALUES (1,2889,32145436768,'CR')
INSERT INTO AccountDeatails (ACC_NO,AMOUNT,TRANSACTION_REF,TRASACTION_TYPE) VALUES (3,6619,321454336768,'CR')
INSERT INTO AccountDeatails (ACC_NO,AMOUNT,TRANSACTION_REF,TRASACTION_TYPE) VALUES (2,4689,32145366768,'CR')
INSERT INTO AccountDeatails (ACC_NO,AMOUNT,TRANSACTION_REF,TRASACTION_TYPE) VALUES (1,89,3214332246768,'DB')
INSERT INTO AccountDeatails (ACC_NO,AMOUNT,TRANSACTION_REF,TRASACTION_TYPE) VALUES (3,269,321344366768,'CR')
INSERT INTO AccountDeatails (ACC_NO,AMOUNT,TRANSACTION_REF,TRASACTION_TYPE) VALUES (1,59,324466768,'CR')
INSERT INTO AccountDeatails (ACC_NO,AMOUNT,TRANSACTION_REF,TRASACTION_TYPE) VALUES (4,2349,321454566768,'CR')
INSERT INTO AccountDeatails (ACC_NO,AMOUNT,TRANSACTION_REF,TRASACTION_TYPE) VALUES (1,2619,3214576576768,'CR')
INSERT INTO AccountDeatails (ACC_NO,AMOUNT,TRANSACTION_REF,TRASACTION_TYPE) VALUES (2,269,32145246768,'CR')
INSERT INTO AccountDeatails (ACC_NO,AMOUNT,TRANSACTION_REF,TRASACTION_TYPE) VALUES (1,29,23432545436,'DB')
INSERT INTO AccountDeatails (ACC_NO,AMOUNT,TRANSACTION_REF,TRASACTION_TYPE) VALUES (4,211,23435345436,'CR')
INSERT INTO AccountDeatails (ACC_NO,AMOUNT,TRANSACTION_REF,TRASACTION_TYPE) VALUES (2,224,2353545436,'DB')
INSERT INTO AccountDeatails (ACC_NO,AMOUNT,TRANSACTION_REF,TRASACTION_TYPE) VALUES (3,500,2343253535436,'DB')
INSERT INTO AccountDeatails (ACC_NO,AMOUNT,TRANSACTION_REF,TRASACTION_TYPE) VALUES (1,212,23432135436,'CR')

--LEFT JOIN
CREATE TABLE Employee
(EmpID INT IDENTITY(1,1) PRIMARY KEY,
EmpName       VARCHAR(100),
BranchId      INT,
SSN           VARCHAR(20),
Managerid     INT,
Email         VARCHAR(100),
City          VARCHAR(100)
)

SELECT * FROM Employee

INSERT into Employee (EmpName, BranchId, SSN, Managerid, Email, City)
VALUES ( 'Jason Telereski', 1, '980-098-9862', NULL, 'Jason@Gmail.com', 'New york')

INSERT into Employee (EmpName, BranchId, SSN, Managerid, Email, City)
VALUES ( 'Narayana Kumar', 1, '530-099-3445', 1, 'Narayana@Gmail.com', 'New york')

INSERT into Employee (EmpName, BranchId, SSN, Managerid, Email, City)
VALUES ( 'Erik darwin', 1, '522-245-8176', 2, 'Erik@Gmail.com', 'Chicago')

INSERT into Employee (EmpName, BranchId, SSN, Managerid, Email, City)
VALUES ( 'Joanna Aiken', 1, '871-901-3286', 2, 'Joanna@Gmail.com', 'Washington')

INSERT into Employee (EmpName, BranchId, SSN, Managerid, Email, City)
VALUES ( 'Laura Cassily', 1, '343-400-8007', 2, 'Laura@Gmail.com', 'Washington')

INSERT into Employee (EmpName, BranchId, SSN, Managerid, Email, City)
VALUES ( 'Jim Carrole', 1, '322-230-6117', 3, 'Jimc@Gmail.com', 'Washington')

INSERT into Employee (EmpName, BranchId, SSN, Managerid, Email, City)
VALUES ( 'Jim Carrole', 1, '343-400-8007', 4, 'Jimc@Gmail.com', 'Washington')

SELECT E1.EmpID, E1.EmpName,E1.SSN,E1.Email,E1.City,E2.EmpName AS MANAGER
FROM Employee E1 LEFT JOIN Employee E2 ON E1.Managerid=E2.EmpID


SELECT M.EmpName FROM Employee M WHERE M.EmpID =(SELECT E.Managerid FROM Employee E WHERE E.EmpID=7) 


SELECT M.* FROM Employee M WHERE M.EmpID IN ( SELECT E.EmpID FROM Employee E WHERE E.City='New York')

SELECT E.* FROM Employee E WHERE EXISTS (SELECT 1 FROM Employee M WHERE E.Managerid=M.EmpID AND M.City='Washington')

CREATE OR ALTER VIEW VW_EMP
AS
SELECT E1.EmpID, E1.EmpName,E1.SSN,E1.Email,E1.City,E2.EmpName AS MANAGER
FROM Employee E1 LEFT JOIN Employee E2 ON E1.Managerid=E2.EmpID


SELECT * FROM VW_EMP
SELECT E.EmpName,V.MANAGER FROM Employee E,VW_EMP V WHERE V.EmpID=E.Managerid

SELECT * FROM ACCOUNT
SELECT * FROM AccountDeatails

UPDATE ACCOUNT 
SET BALANCE =(SELECT DIFF ,CASE WHEN (TRANSACTION_TYPE='CR') THEN BALANCE+AMOUNT
													ELSE BALANCE-AMOUNT 
													END 'DIFF'
										FROM AccountDeatails group by ACC_NO)

SELECT A.ACC_NO.A.BALANCE ,CASE WHEN (AD.TRASACTION_TYPE='CR') THEN UPDATE A SET A.BALANCE+=AD.AMOUNT WHERE A.ACC_NO=AD.ACC_NO
													ELSE UPDATE A SET A.BALANCE-=AD.AMOUNT WHERE A.ACC_NO=AD.ACC_NO
													END 'DIFF' 
													FROM AccountDeatails AD,ACCOUNT A  AS TEMP GROUP BY A.ACC_NO

SELECT * from account(UPDATE A  
SET A.BALANCE = CASE AD.TRASACTION_TYPE  
WHEN 'CR' THEN A.BALANCE+AD.AMOUNT 
WHEN 'DB' THEN A.BALANCE-AD.AMOUNT 
ELSE NULL  
END  
FROM ACCOUNT A,AccountDeatails AD GROUP BY ACC_NO)

SELECT * FROM ACCOUNT A WHERE A.ACC_NO IN(UPDATE A 
SET A.BALANCE =(CASE WHEN (TRANSACTION_TYPE='CR') THEN A.BALANCE+AMOUNT
													ELSE BALANCE-AMOUNT 
													END 'DIFF'
										FROM AccountDeatails group by ACC_NO)


SELECT *,CASE WHEN (AD.TRANSACTION_TYPE='CR') THEN A.BALANCE+AD.AMOUNT 
				ELSE A.BALANCE-AD.AMOUNT 
				END 'DIFF'
FROM ACCOUNT A ,AccountDeatails AD group by (A.ACC_NO)		


SELECT * from account A INNER JOIN AccountDeatails AD ON A.AACC_NO=AD.ACC_NO WHERE EXISTS (UPDATE ACCOUNT  
SET BALANCE =( CASE AD.TRASACTION_TYPE  
WHEN 'CR' THEN A.BALANCE+AD.AMOUNT 
ELSE A.BALANCE-AD.AMOUNT   
END ) 

UPDATE ACCOUNT SET BALANCE =( SELECT AD.AMOUNT,CASE AD.TRASACTION_TYPE  
WHEN 'CR' THEN A.BALANCE+AD.AMOUNT 
ELSE A.BALANCE-AD.AMOUNT   
END
FROM ACCOUNT A,AccountDeatails AD)


UPDATE ACCOUNT A JOIN AccountDeatails AD ON A.AACC_NO=AD.ACC_NO SET BALANCE =( SELECT AD.AMOUNT,CASE AD.TRASACTION_TYPE  
WHEN 'CR' THEN A.BALANCE+AD.AMOUNT 
ELSE A.BALANCE-AD.AMOUNT   
END

 CREATE OR ALTER VIEW TEMP_TAB
AS 
SELECT * FROM Account a where a.ACC_NO in ( select ACC_NO from AccountDeatails );

select * from TEMP_TAB


create or alter view temp_tab 
as
select * from ACCOUNT  inner join AccountDeatails 
on account.ACC_NO = AccountDeatails.ACC_NO;

UPDATE Account JOIN AccountDeatails 
ON ACCOUNT.ACC_NO=AccountDeatails.ACC_NO
SET ACCOUNT.Balance = 
    CASE AD.TRASACTION_TYPE
         WHEN 'CR' THEN ACCOUNT.Balance + AccountDeatails.Amount
         ELSE ACCOUNT.Balance - AccountDeatails.Amount
    END		
	
SELECT * FROM AccountDeatails;