UPDATE ACCOUNT SET BALANCE=5000 where CUST_ID=101
UPDATE ACCOUNT SET BALANCE=4500 where CUST_ID=103

ALTER TABLE CUSTOMER ADD PINCODE VARCHAR(10);
UPDATE CUSTOMER SET PINCODE=574118 where CUST_ID=103;
ALTER TABLE CUSTOMER ALTER COLUMN PINCODE INT;
ALTER TABLE CUSTOMER DROP COLUMN PINCODE;


BEGIN
	SET IDENTITY_INSERT CUSTOMER ON
	INSERT INTO CUSTOMER (CUST_ID,LAST_NAME,FIRST_NAME,ADDRSS,PHONE,AGE,EMAIL)VALUES(101,'RAJ','SHARMA','BIHAR,ORISSA',7895232357,35,'Dghghgfiu@gmail.com')
	INSERT INTO CUSTOMER (CUST_ID,LAST_NAME,FIRST_NAME,ADDRSS,PHONE,AGE,EMAIL)VALUES(128,'RAI','SHAM','MAHARASTRA,PUNE',789532157,48,'akjzwjuhkjlk@gmail.com')
	SET IDENTITY_INSERT CUSTOMER OFF
END
BEGIN
	SET IDENTITY_INSERT CUSTOMER ON
	INSERT INTO ACCOUNT (ACC_TYPE, BALANCE, CUST_ID) VALUES ('SAVINGS',2000,101)
	INSERT INTO ACCOUNT (ACC_TYPE, BALANCE, CUST_ID) VALUES ('SAVINGS',2000,101)
	SET IDENTITY_INSERT CUSTOMER OFF
END

