SELECT FIRST_NAME,AGE,ADDRSS,EMAIL,
CASE WHEN (AGE BETWEEN 0 AND 20) THEN 'MY AGE IS '+CONVERT(CHAR(2),AGE)+' AND I AM  KID'
	WHEN AGE BETWEEN 21 AND 60 THEN 'MY AGE IS '+CONVERT(CHAR(2),AGE)+' AND I AM WORKING'
	ELSE 'MY AGE IS '+CONVERT(CHAR(2),AGE)+' AND I AM WORKING'
	END "AGE CATEGORY"
FROM CUSTOMER

SELECT *,
CASE WHEN (BALANCE<10000) THEN 'BAD ACCOUNT'
	WHEN (BALANCE>10000 AND BALANCE<50000) THEN 'AVERAGE ACCOUNT'
	WHEN BALANCE>50000 THEN +'GOOD ACCOUNT'
	END "COMMENT"
FROM ACCOUNT


SELECT COUNT(CASE WHEN AGE BETWEEN 0 AND 20 THEN 1 ELSE NULL END) AS [0-20],
        COUNT(CASE WHEN AGE BETWEEN 21 AND 40 THEN 1 ELSE NULL END) AS [20-40],
        COUNT(CASE WHEN AGE BETWEEN 41 AND 60 THEN 1 ELSE NULL END) AS [40-60],
		COUNT(CASE WHEN AGE>61 THEN 1 ELSE NULL END) AS [>60]
 FROM CUSTOMER

SELECT CATEGORY, COUNT(AGE) AGE_FREQ
FROM( SELECT AGE,CASE WHEN (AGE BETWEEN 0 AND 20) THEN '[0-20]'
				 WHEN AGE BETWEEN 20 AND 40 THEN '[20-40]'
				 WHEN AGE BETWEEN 40 AND 60 THEN '[40-60]'
				ELSE '[>60]'
				END 'CATEGORY'
FROM CUSTOMER ) AS TEMP GROUP BY(CATEGORY) 

SELECT COUNT(AGE),CASE WHEN (AGE BETWEEN 0 AND 20) THEN '[0-20]'
				 WHEN AGE BETWEEN 20 AND 40 THEN '[20-40]'
				 WHEN AGE BETWEEN 40 AND 60 THEN '[40-60]'
				ELSE '[>60]'
				END 'CATEGORY'
FROM CUSTOMER
/*BEGIN
DECLARE @CUST_ID INT
INSERT INTO CUSTOMER (LAST_NAME,FIRST_NAME,ADDRSS,PHONE,AGE) VALUES ('SHET','BIRA','TAMILNADU,TELANGANA',9789032657,60);
SET  @CUST_ID =@@IDENTITY
PRINT  @CUST_ID
SET  @CUST_ID=SCOPE_IDENTITY()
PRINT  @CUST_ID
END

UPDATE ACCOUNT SET BALANCE+=10000;
UPDATE ACCOUNT SET BALANCE+=10000*0.5 WHERE ACC_TYPE='SAVINGS'
SELECT * FROM ACCOUNT;

DELETE FROM CUSTOMER WHERE CUST_ID=104;
SELECT TOP 50 FROM CUSTOMER


BEGIN
DELETE FROM CUSTOMER WHERE CUST_ID IN (SELECT CUST_ID FROM ACCOUNT);
BEGIN
ROLLBACK TRAN;
END

TRUNCATE  TABLE MODAC

SELECT * FROM CUSTOMER ORDER BY AGE 
SELECT * FROM CUSTOMER ORDER BY AGE DESC
SELECT * FROM CUSTOMER ORDER BY FIRST_NAME

SELECT ACC_TYPE ,COUNT(*) ,MIN(BALANCE),MAX(BALANCE),SUM(BALANCE),AVG(BALANCE)
FROM ACCOUNT 
GROUP BY ACC_TYPE

SELECT ACC_TYPE ,COUNT(*) AS COUNT,MIN(BALANCE) AS "MIN BALANCE",MAX(BALANCE) "MAX BALANCE",SUM(BALANCE) TOTAL_BALANCE,AVG(BALANCE) AVG
FROM ACCOUNT 
GROUP BY ACC_TYPE

SELECT ACC_TYPE ,COUNT(*) AS COUNT,MIN(BALANCE) AS "MIN BALANCE",MAX(BALANCE) "MAX BALANCE",SUM(BALANCE) TOTAL_BALANCE,AVG(BALANCE) AVG
FROM ACCOUNT 
GROUP BY ACC_TYPE
HAVING COUNT(*)>1

SELECT A.ACC_TYPE ,COUNT(*) AS COUNT,MIN(A.BALANCE) AS "MIN BALANCE",MAX(A.BALANCE) "MAX BALANCE",SUM(A.BALANCE) TOTAL_BALANCE,AVG(A.BALANCE) AVG
FROM ACCOUNT AS A 
GROUP BY A.ACC_TYPE

SELECT*,
CASE WHEN (AGE BETWEEN 0 AND 10) THEN 'KIDS'
	WHEN AGE BETWEEN 11 AND 19 THEN 'TEENAGE'
	WHEN AGE BETWEEN 20 AND 30 THEN 'YOUTH'
	WHEN AGE BETWEEN 30 AND 60 THEN 'ADULT'
	WHEN AGE BETWEEN 60 AND 70 THEN 'OLD'
	ELSE 'RETIRED'
	END "AGE CATEGORY"
FROM CUSTOMER

SELECT * INTO MODCUST FROM CUSTOMER WHERE AGE<50

SELECT * FROM CUSTOMER
UNION
SELECT * FROM MODCUST

SELECT * INTO MODCUST FROM CUSTOMER WHERE AGE<50
SELECT * FROM CUSTOMER
UNION ALL
SELECT * FROM MODCUST

SELECT * INTO MODCUST FROM CUSTOMER WHERE AGE<50
SELECT * FROM CUSTOMER
INTERSECT
SELECT * FROM MODCUST

SELECT FIRST_NAME,AGE,ADDRSS,EMAIL FROM

SELECT * FROM CUSTOMER
EXCEPT
SELECT * FROM MODCUST*/

